# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: r-spatial
email: edzer.pebesma@uni-muenster.de 
description: > # this means to ignore newlines until "baseurl:"
   R Spatial software projects, ideas, blogs, and other stuff. For leaving comments, you may need to turn Privacy Badger off for this page.
baseurl: "/r-spatial" # the subpath of your site, e.g. /blog
url: "https://edzer.github.io" # the base hostname & protocol for your site
twitter_username: edzerpebesma
github_username:  edzer/r-spatial

# Build settings
markdown: kramdown
